// 从 data/favicon-hashes.json 生成 wasm/hashdb.go（Go map 字面量）。
// 数据源：BishopFox/Favicons（nuclei-templates 提取），更新了数据就跑一次这个。
// 用法: node scripts/generate-hashdb.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const data = JSON.parse(readFileSync(join(ROOT, 'data/favicon-hashes.json'), 'utf8'));

const entries = Object.entries(data)
  .sort((a, b) => Number(a[0]) - Number(b[0]))
  .map(([h, name]) => `\t${h}: ${JSON.stringify(name)},`)
  .join('\n');

const go = `// Code generated by scripts/generate-hashdb.mjs from data/favicon-hashes.json. DO NOT EDIT.
// 数据源: https://github.com/BishopFox/Favicons (data/known_favicons.json)
package main

var builtinHashDB = map[int32]string{
${entries}
}
`;

const out = join(ROOT, 'wasm/hashdb.go');
writeFileSync(out, go);
execSync(`gofmt -w ${out}`);
console.log(`生成 wasm/hashdb.go，共 ${Object.keys(data).length} 条`);
